research_task:
  description: >
    Conduct a thorough research on plant health, growth patterns, and environmental impact. 
    Explore the latest advancements in sustainable agriculture, plant genetics, and soil health. 
    Ensure that the findings are up-to-date and relevant to the agricultural community in {current_year}.
  expected_output: >
    A list with 10 bullet points highlighting the most critical insights, trends, and discoveries 
    in plant research, including references to sources if available.
  agent: researcher

reporting_task:
  description: >
    Analyze and compile the research findings into a structured report. 
    Expand on each bullet point with scientific explanations, data interpretations, and practical applications. 
    Ensure clarity for researchers, farmers, and policymakers.
  expected_output: >
    A comprehensive, well-organized report with sections dedicated to key findings, 
    potential applications, and recommendations for the agricultural sector. 
    The report should be formatted in markdown without '```'.
  agent: reporting_analyst

blog_writing_task:
  description: >
    Craft a compelling and well-structured blog post that transforms research findings 
    into an engaging and informative article. The blog should be written in a 
    conversational yet professional tone, making complex plant research easy to understand.  
    Focus on real-world applications, sustainable farming techniques, and innovative 
    discoveries in plant science. Ensure the blog flows naturally with smooth transitions 
    between sections, keeping the reader engaged from start to finish.

  expected_output: >
    A high-quality blog post of 400-600 words, formatted in markdown, featuring:  
    - A **captivating introduction** that hooks the reader and introduces the topic.  
    - **Key research findings** presented in a structured and digestible format.  
    - **Real-world applications** or benefits of the research.  
    - **A strong conclusion** that provides key takeaways and encourages further discussion.  
    - Proper use of headings, bullet points, and formatting for readability.  

  agent: blog_writer
